### ISSUE TITLE
SAP dataの格納場所をdatabricksのroot bucketに変更する

### ISSUE THREAD

**Issue by skotani-db** [skotani-db/SAP-demand-forecast-on-databricks#1]
instance profileやunity catalogで接続するのは大変なので、直接root bucketに入れていくのが良いのではと思っています

**Comment by kmotohas** [comment]
@skotani-db こちらはSAPに接続できない場合のworkaroundのお話ですか？
多分、AWSが管理しているワークショップ用の公開S3バケットにparquetを置いておいておくことになるかなと思ってます。
公開であれば直接AutoLoaderで読むなり、root bucketにコピーするのは特別な設定いらないかと思いますが、どうでしょう？

**Comment by kmotohas** [comment]
AppFlowから直接databricksのroot bucketにインポートするってことですね。いいと思います。

**Comment by skotani-db** [comment]
いえ、Appflowの取り込み先のS3 bucketの設定です。databricksをデプロイした時のs3 bucketのdbfs root配下、もしくは自前で用意した別のbucketを使うかがオプションです。前者であれば特に接続情報の設定は不要ですが、後者であればinstance profile or Unity Catalogでの設定が必要になります。

SAPに接続できない場合、公開S3bucketから読むことになりますね。公開bucketであればアクセスキーの設定は必要ないですか？

**Comment by kmotohas** [comment]
公開であればwgetとかでも持ってこれるようなものなのでアクセキーなくても大丈夫かと思いますが、一応検証してみましょう。

**Comment by skotani-db** [comment]
wgetでの着弾先をAppflowの着弾先bucketと合わせればその後の処理コードも統一化できそうですね

**Comment by kmotohas** [comment]
ですね。データをまずroot bucketに置くというのはdatabricks以前の[data ingestionパート](https://github.com/skotani-db/SAP-demand-forecast-on-databricks/tree/main/content/09-end-to-end-workshop/01-data-ingestion)で行うことかと思うので、そこは手順書の中で統一するようにします。
