### ISSUE TITLE
事前にChampionにドライランしてもらう

### ISSUE THREAD

**Issue by kmotohas** [skotani-db/SAP-demand-forecast-on-databricks#4]

**Comment by skotani-db** [comment]
# 背景
AppFlow のフローを作れない問題は SAP 側の負荷というより参加者環境が原因？たまに社用 PC でハンズオンするとセキュリティソフトの問題か、うまく AWS コンソールを叩けないことがある。
そういう事象が発生したらすぐ Option 2 に移るのが良さそう

事前にchampionにドライランしてもらえたらそうする
AppFlowのgetting startedなど、最低限のチェックはお願いしたい

**Comment by skotani-db** [comment]
ACN のチャンピオン候補に依頼する

**Comment by kmotohas** [comment]
作業時間取れそうな時間がわかったら教えてください。

**Comment by kmotohas** [comment]
12/7 (木) に作業してもらうのでアカウント払い出す。
