### ISSUE TITLE
Databricksのラボの前に概念図を示す

### ISSUE THREAD

**Issue by kmotohas** [skotani-db/SAP-demand-forecast-on-databricks#7]
- どういうモデルを作るために、どういうテーブルを作るか、そのために、raw dataを変換していく、可視化してデータを理解していくという流れ
- Unity CatalogやVolumeのそもそもの概念

**Comment by skotani-db** [comment]
https://docs.google.com/presentation/d/1MsGkIyxCoJq_OSP-EVps-hAyW7TTXFazQ_NFxxe1pKo/edit#slide=id.g2a57707bc5f_0_7548
